ccc;

%% Path
dataNoGapped = load("..\DATA\MAT DATA\figure\Res A1 (Temporal-Parietal-Occipital) compare.mat");
dataGapped = load("..\DATA\MAT DATA\figure\Res A2 (Temporal-Parietal-Occipital).mat");

%% 
ICIREG = dataGapped.ICIsREG;

figure;
mSubplot(1, 2, 1, "shape", "square-min");
errorbar((1:length(ICIREG)) - 0.05, ...
         cellfun(@mean, dataGapped.RM_delta_changePeakREG), ...
         cellfun(@SE, dataGapped.RM_delta_changePeakREG), ...
         "Color", "r", "LineWidth", 2, "DisplayName", "Gapped");
hold on;
errorbar((1:length(ICIREG)) + 0.05, ...
         cellfun(@mean, dataNoGapped.RM_delta_changePeakREG), ...
         cellfun(@SE, dataNoGapped.RM_delta_changePeakREG), ...
         "Color", "b", "LineWidth", 2, "DisplayName", "No-Gapped");
legend("Location", "northwest");
ylabel("\DeltaRM (\muV)");
xlabel("T2 ICI (ms)");
title("\DeltaRM Tuning of Peak Response");
xticks(1:length(ICIREG));
xticklabels(num2str(ICIREG));

mSubplot(1, 2, 2, "shape", "square-min");
errorbar((1:length(ICIREG)) - 0.05, ...
         cellfun(@mean, dataGapped.RM_delta_changeTroughREG), ...
         cellfun(@SE, dataGapped.RM_delta_changeTroughREG), ...
         "Color", "r", "LineWidth", 2, "DisplayName", "Gapped");
hold on;
errorbar((1:length(ICIREG)) + 0.05, ...
         cellfun(@mean, dataNoGapped.RM_delta_changeTroughREG), ...
         cellfun(@SE, dataNoGapped.RM_delta_changeTroughREG), ...
         "Color", "b", "LineWidth", 2, "DisplayName", "No-Gapped");
legend("Location", "northwest");
ylabel("\DeltaRM (\muV)");
xlabel("T2 ICI (ms)");
title("\DeltaRM Tuning of Trough Response");
xticks(1:length(ICIREG));
xticklabels(num2str(ICIREG));

%% 
res_tuning_Peak = [cellfun(@mean, dataGapped.RM_delta_changePeakREG), ...
                   cellfun(@SE, dataGapped.RM_delta_changePeakREG), ...
                   cellfun(@mean, dataNoGapped.RM_delta_changePeakREG), ...
                   cellfun(@SE, dataNoGapped.RM_delta_changePeakREG)];

res_tuning_Trough = [cellfun(@mean, dataGapped.RM_delta_changeTroughREG), ...
                     cellfun(@SE, dataGapped.RM_delta_changeTroughREG), ...
                     cellfun(@mean, dataNoGapped.RM_delta_changeTroughREG), ...
                     cellfun(@SE, dataNoGapped.RM_delta_changeTroughREG)];
